### ISSUE TITLE
Firefox's extensions.webextensions.remote=false doesn't apply/store the settings

### ISSUE THREAD

**Issue by peter-lyons-kehl** [Darkempire78/Github1s-Extension#14]
Thank you for this time-saver.

Unfortunately, (at least in) Firefox the "Button title" preference doesn't apply:
![image](https://user-images.githubusercontent.com/4270240/123873377-43b85480-d8eb-11eb-9dfb-27029838dfe9.png)
-> I did click "Save options."

![image](https://user-images.githubusercontent.com/4270240/123873435-55016100-d8eb-11eb-9c7a-07415ad9e39b.png)
-> I did refresh the page with Ctrl+R - but all the same.

**Comment by clementwzk** [comment]
@peter-kehl It works well for me 🤔  
Are your sure you clicked on the "Save Options" button ?

**Comment by peter-lyons-kehl** [comment]
Apologies. That was because I had Firefox `about:config` >> `extensions.webextensions.remote` set to `false`. That made Firefox not apply/store the add-on's preferences. As per https://bugzilla.mozilla.org/show_bug.cgi?id=1419341 it's unsupported.

**Comment by clementwzk** [comment]
np
