### ISSUE TITLE
publish on the Store?

### ISSUE THREAD

**Issue by huntertran** [Darkempire78/Github1s-Extension#2]
Great extension. Would you consider publishing it on Chrome Web Store and Firefox Add-on?

Also, it would be great if you could post it to Microsoft Store to support Chromium Edge as well

**Comment by clementwzk** [comment]
I sent a request to Firefox, we have to wait now

**Comment by clementwzk** [comment]
It is necessary to pay $5 to publish on chrome :/

**Comment by clementwzk** [comment]
available on the Firefox market : https://addons.mozilla.org/fr/firefox/addon/github1s-extension/

**Comment by kiprasmel** [comment]
one can create .xpi & .crx files for firefox & chrome respectively and provide them with a link from readme at the releases page

**Comment by clementwzk** [comment]
@kiprasmel The extension is already available on the Firefox marketplace, but yes why not
