### ISSUE TITLE
firefox : option error

### ISSUE THREAD

**Issue by kbwo** [Darkempire78/Github1s-Extension#4]
I use Firefox Developer Edition / macOS

Download the repository
Go to about:debugging#/runtime/this-firefox
Click on Loading a temporary add-on
Select the repository content.js file

Done these steps, but "View on Github1s" button don't appear.
Is there any solution?

**Comment by clementwzk** [comment]
Yes it's true.
I already fix the options but it's does not works

**Comment by clementwzk** [comment]
The option storage seems do not works

**Comment by clementwzk** [comment]
i fixed it, it's working now. But options do not works on firefox for the moment

**Comment by clementwzk** [comment]
fixed if you use the version of the market
