### ISSUE TITLE
"View on Github1s" button don't appear on Chrome

### ISSUE THREAD

**Issue by jfzhang95** [Darkempire78/Github1s-Extension#5]
After setting up the extension, the "View on Github1s" button don't appear on Chrome.

**Comment by clementwzk** [comment]
Since the installation of the extension, the button has never appeared?

**Comment by jfzhang95** [comment]
Yes, I cannot see the button.

**Comment by clementwzk** [comment]
Check if there is an error here `chrome://extensions/`
![image](https://user-images.githubusercontent.com/50015928/107854107-0a8ab680-6e1a-11eb-9a90-c7cef1df31c4.png)

**Comment by jfzhang95** [comment]
Hi, I can see the button now. I did not save the options previously. Thanks for the great work!
