### ISSUE TITLE
could not get it to work by simply downloading directly from firefox store..

### ISSUE THREAD

**Issue by hpl002** [Darkempire78/Github1s-Extension#6]
title says it

However, adding the file directly was as easy as downloading it, so not a huge deal

---
Have attempted to disable all other extensions and also opening in private tab(ensuring that the ext is enabled in private tabs) to ensure that this isnt some odd caching problem. Still nothing.

**Comment by clementwzk** [comment]
Works if you download from the repo ?

**Comment by hpl002** [comment]
yes

**Comment by clementwzk** [comment]
Try with the new version 1.0.5

**Comment by clementwzk** [comment]
works?
